Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
