
costs:
  increase_hp: 30
  increase_range: 30
  shoot: 10
  move: 5

daily_energy: 10

rewards:
  heart: 3
  energy_cell: 30

# This is the max on the X and Y axis.
# It calculated as number of players + this number
# This is max X and Y and counting starts at 0 not 1
# So effectively the world size is Players + Number below + 1
world_size_max:
  default: 2
